### ISSUE TITLE
RaspberryPi/ARM compatible

### ISSUE THREAD

**Issue by mainiak** [fyne-io/desktop#2]
Hi. Is Fyne Desktop RasberryPi/ARM compatible? Will be?

RaspberryPi/ARM compatible

**Comment by andydotxyz** [comment]
We will add ARM / Raspberry Pi compatibility yes :)
It will need the 1.2 version of Fyne which does not yet have a release date but will be some months away.

**Comment by andydotxyz** [comment]
This is now working when using Fyne from the develop branch.
If you turn off module support and update your fyne checkout to "develop" branch then the desktop project should work on ARM (through the GLES backend).

Once Fyne 1.2 is released (not yet scheduled) this will work out of the box

**Comment by mainiak** [comment]
How one turns module support off?

**Comment by andydotxyz** [comment]
export go111module=off
