### ISSUE TITLE
Add full application switcher

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/desktop#29]
Not just alt-tab but a visual indicator, at least with icons, possibly with previews?

**Comment by okratitan** [comment]
Agreed - Previews will need compositing though I think?

**Comment by andydotxyz** [comment]
It might be possible to do without compositing, but a version with just icons would rock :)

**Comment by andydotxyz** [comment]
This could be resolved by branch feature/appSwitcher and PR #77.

**Comment by andydotxyz** [comment]
I'm going to call this done :) Adding other features to it could be enhancement tickets later
