### ISSUE TITLE
Cannot install following the instructions 1:1

### ISSUE THREAD

**Issue by probonopd** [fyne-io/desktop#36]
Following the instructions to the letter, on Ubuntu 18.04.2 LTS using go version go1.13.3 linux/amd64, getting

![what](https://user-images.githubusercontent.com/2480569/68056304-b0301a00-fcea-11e9-8bd9-25fc5b4d50e7.png)

![get](https://user-images.githubusercontent.com/2480569/68056299-ad352980-fcea-11e9-9d51-fbcf8c7fff5c.png)

Please update the readme with instructions that can be used 1:1 with copy and paste, without having to "mess around". Thanks!

**Comment by andydotxyz** [comment]
Can you confirm whether or not you have updated any go module configuration or go environment settings?

**Comment by probonopd** [comment]
No, I have not made any changes. Just verified by running a Xubuntu Live ISO, and installing Go following https://golang.org/doc/install.

**Comment by andydotxyz** [comment]
Ok thanks. I had thought the default configuration of Go 1.13 would have worked out of the box. I’ll see what we can do to simplify.

**Comment by andydotxyz** [comment]
Improved process and updated README should address this issue.

**Comment by probonopd** [comment]
Thank you.
