### ISSUE TITLE
Some SVGs can cause crashes

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/desktop#5]
This may be an issue within fyne.
We need to capture a crashing SVG to debug further

**Comment by okratitan** [comment]
https://paste.fedoraproject.org/paste/NC8mGbjmHxKcewz5881NCw

**Comment by andydotxyz** [comment]
Added a crash handler in fyne-io/fyne@7c56bda some oksvg library fixes are also in PR srwiley/oksvg#14 which we can land into our vendor folders and modules once it's accepted.
