### ISSUE TITLE
Some icons don't work in title bars and/or the app bar

### ISSUE THREAD

**Issue by okratitan** [fyne-io/desktop#54]
For me, in my app bar, the goland and minecraft-launcher icons do not work - I think this is probably a bug with our svg handler.

Also - the xterm icon does not work in the window borders - this is a pixmap found through icccm/ewmh hints.  This is related to some transparency hints/fixes that @andydotxyz and I already worked on to make other icons work - such as xeyes and fyne examples icons.

See the screenshot below for an example of these issues:
[https://imgur.com/20ZZxIs](https://imgur.com/20ZZxIs)

**Comment by andydotxyz** [comment]
What do you see instead of the goland icon?
Here I see the icon as expected so I'm unsure on this one. Which icon theme is loaded?

**Comment by okratitan** [comment]
Look at the screenshot and the goland icon in the app bar... it is missing the white GO _ text that the actual icon has.  With minecraft as you can see in the app bar,  it is just completely black.  And then of course the xterm issue.

**Comment by andydotxyz** [comment]
The minecraft icon does not work because oksvg (the library we use) does not support "class" attributes yet.
Opened fyne-io/fyne#585.

**Comment by andydotxyz** [comment]
Goland is working OK at my end, probably because it specifies a PNG in the .desktop - what is your equivalent file content?

```
[Desktop Entry]
...
Name=GoLand
Icon=/opt/GoLand-2019.3/bin/goland.png
```

**Comment by andydotxyz** [comment]
Pushed the fix upstream https://github.com/BurntSushi/xgbutil/pull/48
