### ISSUE TITLE
Window move is very slow with Jetbrains apps or items that cover it's window

### ISSUE THREAD

**Issue by andydotxyz** [fyne-io/desktop#59]
This was better a few weeks ago - I think it has slowed down since the XRandR code additions.

Drag any window, move it around the desktop, notice a significant lag in where the window is to where the pointer has moved to.

**Comment by okratitan** [comment]
It is still very fast for me - the one addition I'm seeing is when goland is visible and the window is on top of goland ... and/or goland itself.  I think it has something to do with goland redrawing and us actually providing it correct coordinates now?  I'm not sure.  But I only see it in those two cases.

**Comment by andydotxyz** [comment]
Quite right.
Perhaps the updated code is telling GoLand that it has a new width and height when in actual fact it's just a new position?

**Comment by andydotxyz** [comment]
I tried removing the width/height but of course for configureNotify it's required :(

**Comment by andydotxyz** [comment]
This is back :(

**Comment by andydotxyz** [comment]
This strangely seems to get worse the longer that the GoLang window is open!

**Comment by andydotxyz** [comment]
I think I have come to the conclusion that there is little we can do about this until we have a compositor in place.
I think that GoLand response to expose events more slowly over time, and with a compositor we could remove the expose events happening pretty much completely.
