### ISSUE TITLE
How can I use the Chinese font in fyne  ?

### ISSUE THREAD

**Issue by wangshuaismart1** [fyne-io/desktop#73]
I have find  I can use the  Chinese font in NewWindow‘s title ;  but useless in others widget ，
could you help me ?  thanks

我发现窗体的标题可以中文显示，可是其他组件都不能显示中文，请问可以帮忙解决中文在所有组件中都可以显示的问题吗？

**Comment by andydotxyz** [comment]
This is a common request in the toolkit, we are going to find an easier way but for now you can use the FYNE_FONT environment. See discussion at [the duplicate ticket](https://github.com/fyne-io/fyne/issues/297)

**Comment by andydotxyz** [comment]
Closed as duplicate
